[package]
name = "vtpmtest"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.29", features = ["derive"] }
pretty-hex = "0.4.1"
#serde = { version = "1.0.211", features = ["derive"] }
sev = "1.2.1"
sha2 = "0.10.8"
tempfile = "3.13.0"
tss-esapi = "7.5.1"
